CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    category_id BIGINT NOT NULL,
    created_on TIMESTAMP(0)  WITHOUT TIME ZONE NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP(0)  WITHOUT TIME ZONE NOT NULL,
    initiator_id BIGINT NOT NULL,
    lat FLOAT,
    lon FLOAT,
    paid BOOLEAN DEFAULT FALSE NOT NULL,
    participant_limit INTEGER DEFAULT 0 NOT NULL,
    published_on TIMESTAMP(0) WITHOUT TIME ZONE,
    request_moderation BOOLEAN DEFAULT TRUE NOT NULL,
    state VARCHAR(20) NOT NULL,
    title VARCHAR(120) NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id),
    CONSTRAINT fk_events_categories FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_events_users FOREIGN KEY (initiator_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS moderation_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id BIGINT NOT NULL,
    admin_id BIGINT,
    comment_text TEXT NOT NULL,
    created_on TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_moderation_comments PRIMARY KEY (id),
    CONSTRAINT fk_moderation_comments_events FOREIGN KEY (event_id) REFERENCES events (id)
);

CREATE INDEX IF NOT EXISTS idx_category_name ON categories (name);
CREATE INDEX IF NOT EXISTS idx_event_category ON events (category_id);
CREATE INDEX IF NOT EXISTS idx_event_initiator ON events (initiator_id);
CREATE INDEX IF NOT EXISTS idx_event_date ON events (event_date);
CREATE INDEX IF NOT EXISTS idx_event_state ON events (state);
CREATE INDEX IF NOT EXISTS idx_moderation_comments_event ON moderation_comments (event_id);
CREATE INDEX IF NOT EXISTS idx_moderation_comments_created ON moderation_comments (created_on);

COMMENT ON TABLE categories IS 'Таблица категорий событий';
COMMENT ON TABLE users IS 'Таблица пользователей';
COMMENT ON TABLE events IS 'Таблица событий';

COMMENT ON INDEX idx_category_name IS 'Индекс для быстрого поиска категорий по имени';
COMMENT ON INDEX idx_event_category IS 'Индекс для поиска событий по категории';
COMMENT ON INDEX idx_event_initiator IS 'Индекс для поиска событий по организатору';
COMMENT ON INDEX idx_event_date IS 'Индекс для сортировки и фильтрации событий по дате';
COMMENT ON INDEX idx_event_state IS 'Индекс для фильтрации событий по состоянию';
COMMENT ON TABLE moderation_comments IS 'Таблица замечаний при модерации событий';
COMMENT ON COLUMN moderation_comments.event_id IS 'ID события, к которому относится замечание';
COMMENT ON COLUMN moderation_comments.admin_id IS 'ID администратора, оставившего замечание';
COMMENT ON COLUMN moderation_comments.comment_text IS 'Текст замечания';
COMMENT ON COLUMN moderation_comments.created_on IS 'Дата создания замечания';
