services:
  postgres:
    image: postgres:15-alpine
    container_name: analyzer-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ewm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  db-init:
    image: postgres:16.1
    container_name: db-init
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint:
      - bash
      - -c
      - |
        echo "Waiting for PostgreSQL..."
        sleep 5
        PGPASSWORD=postgres psql -h postgres -U postgres -d postgres -v ON_ERROR_STOP=1 <<-EOSQL
        CREATE DATABASE stats_stats_server;
        CREATE DATABASE core_main_service;
        CREATE DATABASE core_user_service;
        CREATE DATABASE core_request_service;
        EOSQL
        echo "Databases created successfully"

volumes:
  postgres_data:
