version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: analyzer-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ewm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  db-init:
    image: postgres:15-alpine
    container_name: db-init
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint:
      - bash
      - -c
      - |
        echo "Waiting for PostgreSQL..."
        until PGPASSWORD=postgres psql -h postgres -U postgres -d postgres -c '\q'; do
          echo "Postgres is unavailable - sleeping"
          sleep 2
        done

        echo "PostgreSQL is up - creating databases"
        PGPASSWORD=postgres psql -h postgres -U postgres -d postgres <<-EOSQL
        SELECT 'CREATE DATABASE stats_stats_server'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'stats_stats_server')\gexec

        SELECT 'CREATE DATABASE core_user_service'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'core_user_service')\gexec

        SELECT 'CREATE DATABASE core_request_service'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'core_request_service')\gexec

        SELECT 'CREATE DATABASE core_event_service'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'core_event_service')\gexec
        
        SELECT 'CREATE DATABASE ewm_analyzer'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'ewm_analyzer')\gexec

        SELECT 'CREATE DATABASE core_category_service'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'core_category_service')\gexec
        EOSQL

        echo "Databases ensured (created if missing)"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: analyzer-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: analyzer-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Kafka listeners
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      # single broker setup
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres_data:
