spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: category-main-service
          uri: lb://main-service
          predicates:
            - Path=/admin/categories/*
        - id: user-main-service
          uri: lb://main-service
          predicates:
            - Path=/admin/users/**


server:
  port: 8080