spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: user-event-requests-patch
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/events/{eventId}/requests

        - id: user-event-requests-sub
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/events/{eventId}/requests/**

        - id: user-requests
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests,/users/{userId}/requests/**

        - id: admin-categories
          uri: lb://category-service
          predicates:
            - Path=/admin/categories/**,/admin/categories

        - id: admin-users
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**,/admin/users

        - id: admin-compilations
          uri: lb://event-service
          predicates:
            - Path=/admin/compilations/**

        - id: admin-moderation
          uri: lb://event-service
          predicates:
            - Path=/admin/events/moderation,/admin/events/{eventId}/moderate

        - id: admin-events
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**,/admin/events

        - id: public-categories
          uri: lb://category-service
          predicates:
            - Path=/categories/**,/categories

        - id: public-compilations
          uri: lb://event-service
          predicates:
            - Path=/compilations/**,/compilations

        - id: public-events
          uri: lb://event-service
          predicates:
            - Path=/events/**,/events

        - id: user-events
          uri: lb://event-service
          predicates:
            - Path=/users/{userId}/events,/users/{userId}/events/{eventId}


        - id: user-moderation-comments
          uri: lb://event-service
          predicates:
            - Path=/users/{userId}/events/{eventId}/moderation-comments

server:
  port: 8080