CREATE TABLE IF NOT EXISTS endpoint_hits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(512) NOT NULL,
    ip VARCHAR(15) NOT NULL,
    timestamp TIMESTAMP(0) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_endpoint_hits_timestamp ON endpoint_hits (timestamp);
CREATE INDEX IF NOT EXISTS idx_endpoint_hits_app_uri ON endpoint_hits (app, uri);
CREATE INDEX IF NOT EXISTS idx_endpoint_hits_app_timestamp ON endpoint_hits (app, timestamp);
CREATE INDEX IF NOT EXISTS idx_endpoint_hits_uri_timestamp ON endpoint_hits (uri, timestamp);
CREATE INDEX IF NOT EXISTS idx_endpoint_hits_ip ON endpoint_hits (ip);

COMMENT ON TABLE endpoint_hits IS 'Таблица для хранения информации о запросах к эндпоинтам';
COMMENT ON COLUMN endpoint_hits.id IS 'Уникальный идентификатор записи';
COMMENT ON COLUMN endpoint_hits.app IS 'Идентификатор сервиса (например: ewm-main-service)';
COMMENT ON COLUMN endpoint_hits.uri IS 'URI эндпоинта (например: /events/1)';
COMMENT ON COLUMN endpoint_hits.ip IS 'IP-адрес пользователя';
COMMENT ON COLUMN endpoint_hits.timestamp IS 'Дата и время запроса';